# Generated by Django 4.1.3 on 2022-12-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingridient',
            old_name='unit',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingridient',
            old_name='title',
            new_name='name',
        ),
    ]
