# Generated by Django 4.1.3 on 2022-12-25 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_unit_ingridient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridient',
            name='count',
        ),
        migrations.AddField(
            model_name='recipeingridient',
            name='count',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
