# Generated by Django 4.1.3 on 2022-12-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ingridient_count_recipeingridient_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingridient',
            old_name='count',
            new_name='amount',
        ),
    ]
