# Generated by Django 4.1.3 on 2022-12-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_count_recipeingridient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
