# Generated by Django 4.1.3 on 2023-01-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_recipeingridient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingridient',
            options={'verbose_name': 'Ингридиент в рецепте', 'verbose_name_plural': 'Ингридиенты в рецептах'},
        ),
    ]
