# Generated by Django 4.1.3 on 2023-01-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_recipeingridient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient_list', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
