# Generated by Django 4.1.3 on 2023-01-05 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tag_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
