# Generated by Django 4.1.3 on 2023-01-05 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_recipeingridient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество 1!')], verbose_name='Количество'),
        ),
    ]
