# Generated by Django 4.1.3 on 2023-01-05 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_recipeingridient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient_list', to='api.ingridient', verbose_name='Ингридиент'),
        ),
    ]
