# Generated by Django 4.1.3 on 2023-01-08 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_recipeingridient_ingridient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество 1!')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipeingridient',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient', to='api.ingridient', verbose_name='Ингридиент'),
        ),
    ]
