# Generated by Django 4.1.3 on 2023-01-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_recipeingridient_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingridient',
            options={'ordering': ['-id'], 'verbose_name': 'Ингридиент в рецепте', 'verbose_name_plural': 'Ингридиенты в рецептах'},
        ),
    ]
