# Generated by Django 4.1.3 on 2023-01-10 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_recipe_options_alter_recipeingridient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.AddConstraint(
            model_name='recipeingridient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingridient'), name='unique_recipeingridient'),
        ),
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique_recipetag'),
        ),
    ]
